//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class item
    {
        public int id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public Nullable<int> model_id { get; set; }
        [Display(Name = "Name*")]
        [Required]
        [MaxLength(255)]
        [RegularExpression("^[a-zA-Z0-9- ]*$", ErrorMessage = "Only alphanumeric allowed.")]
        public string name { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual model model { get; set; }
    }
}
